### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by abhi1125** [avinassh/cowin-assist#3]
python main.py
  File "main.py", line 176
    if cmd := ctx.match.groupdict().get("cmd_mg"):
            ^
SyntaxError: invalid syntax

**Comment by avinassh** [comment]
You are prolly using older version of Python. 

https://github.com/avinassh/cowin-assist#system-requirements

**Comment by avinassh** [comment]
I am assuming you were able to run, so closing this issue.
